[package]
name = "repeat"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4", features = ["derive"] }
execute = { version = "0" }
create_process_w = { version = "0", package = "CreateProcessW" }
wintrap = "0.3.1"
